steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - deploy/cloud-run/simulator/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/brainbar/simulator
      - .
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/brainbar/simulator
